# Generated by Django 5.2.9 on 2025-12-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='notes',
            new_name='notes_admin_private',
        ),
        migrations.AddField(
            model_name='property',
            name='notes_admin_to_host',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='notes_host',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='notes_host_private',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental_hub_app.property')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental_hub_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes_guest', models.TextField(blank=True, null=True)),
                ('notes_host', models.TextField(blank=True, null=True)),
                ('notes_host_private', models.TextField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_requests', to='rental_hub_app.user')),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canceled_requests', to='rental_hub_app.user')),
                ('finished_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_requests', to='rental_hub_app.user')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rental_hub_app.user')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rental_hub_app.property')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_requests', to='rental_hub_app.user')),
            ],
        ),
    ]
