# Generated by Django 5.2.9 on 2025-12-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_hub_app', '0002_rename_notes_property_notes_admin_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='num_parkings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
