# Generated by Django 5.2.7 on 2025-12-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_hub_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
