# Generated by Django 5.2.9 on 2025-12-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_hub_app', '0003_property_elevator_property_num_parkings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
