# Generated by Django 5.2.9 on 2025-12-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_hub_app', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default='images/default_image.jpg', null=True, upload_to='images/'),
        ),
    ]
