# Generated by Django 5.2.9 on 2025-12-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_hub_app', '0007_alter_property_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
