# Generated by Django 5.2.7 on 2025-12-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_hub_app', '0003_alter_role_table'),
        ('rental_hub_app', '0009_remove_property_image_image'),
    ]

    operations = [
    ]
