# Generated by Django 5.2.7 on 2025-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_hub_app', '0010_merge_20251210_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
    ]
